### ISSUE TITLE
Child process doesn't exit while it reaches its max idle/run times ?

### ISSUE THREAD

**Issue by jiaojie1989** [pythias/Stark#2]
I found an error while using Stark-1.2.6 with PHP-5.5.28(TS build) on Ubuntu-15.10.

Whenever the child process reaches its max run times(max_run_count, max_run_seconds or max_idle_seconds), the code in `src/Stark/Daemon/Worker.php` line 47 `exit` does not work anyhow.

``` php
    public function start() {
        $this->_initialize();
        $this->_startLoop();
        $this->_finalize();

        exit;
    }
```

I want to know if this happens with the signal handlers ?

**Comment by pythias** [comment]
When the worker reaches max run time/count, worker run loop will stop

``` php
    $this->_run = false;
    //...

    private function _startLoop() {
        while ($this->_run) {
            //...
        }
    }
```

Work will exit like this:

```
[2015-12-19 00:52:51] config_1.INFO: No.0 worker restart: Queue limit reached [] []
[2015-12-19 00:52:51] config_1.INFO: Worker 0 is completed [] []
```
